---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03
  namespace: test001
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  #storageClassName: standard
  hostPath:
    #path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/pv03
    path: /mnt/pv003
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pv03
  namespace: test001
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: pv03
  #selector:
  #  name: "pv02"

---
apiVersion: v1
kind: Pod
metadata:
  name: inithtdocs
  namespace: test001
spec:
  restartPolicy: Never
  containers:
  - name: inithtdocs
    image: nmolleruq/ww2inithtdocs:latest

    volumeMounts:
      - mountPath: /opt/webwork/webwork2/htdocs
        name: ww-htdocs

  volumes:
  - name: ww-htdocs
    persistentVolumeClaim:
      claimName: pvc-pv03
